### ISSUE TITLE
Data links in pdf refer to localhost

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/prj.app#1005]
# Problem

After downloading multiple worksheets I navigated to one of the exercise folders and clicked on the download link in the pdf. I expected to get zip file but instead got.

![screenshot 2019-02-15 at 16 20 11](https://user-images.githubusercontent.com/2510900/52862283-97241080-313d-11e9-8a5e-75bcecf16828.png)

# Solution

Fix all links to refer to changelog URL

**Comment by ann26** [comment]
hi @NyakudyaA could you give me the details of which worksheet you found this issue please?

**Comment by NyakudyaA** [comment]
@ann26 I think it's all of them, Let me quickly check them

**Comment by NyakudyaA** [comment]
@ann26 I have tried to check randomly but it seems the issue is fixed. I will close this and will open when I experience this again.
