### ISSUE TITLE
Pad Name Ordering is Not Reliable

### ISSUE THREAD

**Issue by ismailsunni** [kartoza/prj.app#1011]
I saw that the ordering of the version is based on the `pad_version`
```
    def versions(self):
        """Get all the versions for this project."""
        qs = Version.objects.filter(project=self).order_by('-padded_version')
        return qs
```

Unfortunately, the `pad_name` method is not reliable for ordering if the version does not have the standard format (x.y.z). For example `3.4 LTR` and see below the result of the ordering:

![image](https://user-images.githubusercontent.com/1421861/53965733-044e1480-40f2-11e9-809a-7af5ab48f06b.png)

One solution could be set the versioning using the same standard so that the pad_name is realiable for sorting the version.

**Comment by anitanh** [comment]
It's already fixed
![screencapture-changelog-qgis-org-en-qgis-version-list-2020-07-30-14_18_49](https://user-images.githubusercontent.com/26101337/88892824-a2a2c300-d26f-11ea-9059-508b6a780f6f.png)
