### ISSUE TITLE
Cannot login to changelog application

### ISSUE THREAD

**Issue by andreasneumann** [kartoza/prj.app#1017]
Currently I cannot login to the changelog application to change QGIS.ORG sponsor data.

Below is a screenshot of the error I am receiving with the following error id:
bc0ce9f3ca714b5ba966f72ff73525de

![image](https://user-images.githubusercontent.com/884476/59581165-511f8f00-90d4-11e9-8a44-84c0203d6453.png)

**Comment by timlinux** [comment]
Hmm I am getting that too - looking into why now...

**Comment by timlinux** [comment]
Looks like the disk is full...clearing some space....

**Comment by timlinux** [comment]
Space cleared, seems all good again...
