### ISSUE TITLE
Can't enter dates for voting

### ISSUE THREAD

**Issue by timlinux** [kartoza/prj.app#1018]
<img width="823" alt="image" src="https://user-images.githubusercontent.com/178003/60462662-cbf2b900-9c41-11e9-9ee3-3d6911e89e88.png">

http://changelog.qgis.org/en/qgis/committees/qgis-psc/create-ballot/

@ann26 can you come up with a quick fix for that?

**Comment by ann26** [comment]
hi @timlinux that is strange, because the datepicker is working on my side
![Peek 2019-07-02 10-10](https://user-images.githubusercontent.com/26101337/60479921-ccc33380-9cb1-11e9-909d-0126faea8979.gif)
