### ISSUE TITLE
Inconsistent numbering for questions when creating modules

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/prj.app#1022]
# Problem
I am trying to add a new module for QGIS but when I add a question the first one is labeled 1 and the subsequent ones are labeled 4.

![bug](https://user-images.githubusercontent.com/2510900/61458355-98ff3380-a96a-11e9-9dea-96d8c3c4cb30.png)

# Solution
Please fix and make happy

**Comment by ann26** [comment]
hi @NyakudyaA could you give me the link where did you encounter the problem?

**Comment by NyakudyaA** [comment]
> hi @NyakudyaA could you give me the link where did you encounter the problem?

Hi @ann26 Can you please check the following http://changelog.qgis.org/en/qgis/section/symbology-22/detail/81/

**Comment by ann26** [comment]
@NyakudyaA I checked it and I added a question but I couldn't reproduce your problem.
![Screenshot from 2019-11-18 20-57-14](https://user-images.githubusercontent.com/26101337/69058474-53509580-0a46-11ea-9a96-0004fa1df9e0.png)

**Comment by NyakudyaA** [comment]
@ann26 check the numbering system in the example I sent you. I think this only happens when you.
* In situations where you have questions 1 -4, delete question number 2 and add another question.
* Instead of number 3 becoming number 2 the next question you add will automatically become number four which renders you having incorrect numbering

**Comment by ann26** [comment]
hi @NyakudyaA I did as you described but I still didn't get the problem. When I delete question no. 2 from a module with 4 questions, no. 3 became no. 2 and no. 4 became no. 3. Then I added another question, it became no. 4 and didn't affect the numbering of the other questions

**Comment by NyakudyaA** [comment]
Hi @ann26 Please see the following
![questions](https://user-images.githubusercontent.com/2510900/69060289-c8f53b00-0a1f-11ea-816e-4ce361f7afc3.png)

**Comment by NyakudyaA** [comment]
@ann26 
![save](https://user-images.githubusercontent.com/2510900/69060820-b3ccdc00-0a20-11ea-83bb-9eb0c6f14888.gif)

**Comment by ann26** [comment]
@NyakudyaA ok got it, this problem does not occur in Chrome but it does in Firefox
