### ISSUE TITLE
Generated certificate special characters issues for course convener

### ISSUE THREAD

**Issue by tudorbarascu** [kartoza/prj.app#1043]
The generated certificates support special characters except for the course convener (probably other font).
See:
[wrong_characters.pdf](https://github.com/kartoza/prj.app/files/3640982/wrong_characters.pdf)

I manually edited the certificates to bypass this.
Maybe changing the font of the course convener would be a better solution?

**Comment by timlinux** [comment]
Thanks for the report @tudorbarascu . Can you look at this @ann26 ?

**Comment by tudorbarascu** [comment]
This is a general problem; see also:
![problem](https://user-images.githubusercontent.com/3179646/73171146-b88ccb00-4108-11ea-9ca8-8bdce9443e50.png)
and
![problem1](https://user-images.githubusercontent.com/3179646/73171131-b0349000-4108-11ea-8112-bef1faae3410.png)

**Comment by ann26** [comment]
hi @tudorbarascu sorry for the long wait, I have fixed it, please try again. Also should you find your previous certificates with wrong characters please regenerate the certificate using this button as shown in figure below:
![Screenshot from 2020-02-17 16-25-11](https://user-images.githubusercontent.com/26101337/74641830-8bca5180-51a4-11ea-8dba-f7f42d4b31e7.png)

**Comment by tudorbarascu** [comment]
@ann26 Thanks a lot! I checked and the issue is solved only for the verifying workflow. For the pdf's, although I regenerated them it's still an issue. Am I doing something wrong?

**Comment by ann26** [comment]
hi @tudorbarascu could you give me the url and the attendee where the pdf is still not working?

**Comment by tudorbarascu** [comment]
Sure! https://changelog.qgis.org/en/qgis/certifyingorganisation/qgis-qtibia-engineering/course/qgis_waterwastewater-workflows-gis-databases-telemetry-hydraulical-modelling_2020-01-20-2020-01-24/print/961/  The course convener name is the problem, not the attendee name. Thank you again for taking care of this.

**Comment by ann26** [comment]
@tudorbarascu I've fixed it, please check it again.

**Comment by tudorbarascu** [comment]
@ann26 It works now! Great work! Thanks a lot!
