### ISSUE TITLE
[voting] inconsistent view for ballots

### ISSUE THREAD

**Issue by ann26** [kartoza/prj.app#1049]
from @anitagraser

I've checked and the views still seem to disagree:
![image](https://user-images.githubusercontent.com/26101337/66817155-767ab780-ef65-11e9-894e-61db71eab8ea.png)

![image](https://user-images.githubusercontent.com/26101337/66817165-7bd80200-ef65-11e9-9da5-e04b48370574.png)

Also the number of votes cast on a ballot are inconsistent:

![image](https://user-images.githubusercontent.com/26101337/66817201-8b574b00-ef65-11e9-838a-51fd1c28e35f.png)

![image](https://user-images.githubusercontent.com/26101337/66817230-93af8600-ef65-11e9-8700-90c0c576027d.png)

**Comment by anitagraser** [comment]
Thanks for moving this to the issue tracker @ann26
