### ISSUE TITLE
Can't top up credits

### ISSUE THREAD

**Issue by gubuntu** [kartoza/prj.app#1061]
Click the cart to top up credits and nothing happens

![Screenshot 2019-10-22 at 12 37 22](https://user-images.githubusercontent.com/496911/67278267-f5717200-f4c8-11e9-96aa-fb88edac6716.png)

**Comment by timlinux** [comment]
@ann26 can you make a new view for this with the rules:

*. certification managers can add credits in the view
* organisation managers can see a message 'Please contact admin' with a list of avatars and names of certification managers (no emails)
* other users should get a 404 or whatever

**Comment by ann26** [comment]
credit system is already in place
