### ISSUE TITLE
no link to About page

### ISSUE THREAD

**Issue by gubuntu** [kartoza/prj.app#1062]
It should be easy to get to http://changelog.qgis.org/qgis/about/ via the menu or links in other places. 

Currently it's either not there or well hidden

**Comment by gubuntu** [comment]
OK I see it's behind various i buttons but the obvious place for me would be in the main certification menu dropdown

**Comment by timlinux** [comment]
@ann26 will you add a 'Help' menu item in the cert menu pointing to our help doc?

Thanks!

**Comment by anitanh** [comment]
It's in the navigation bar now
![Screenshot from 2020-07-29 14-43-13](https://user-images.githubusercontent.com/26101337/88771919-26927780-d1aa-11ea-9cf8-f3d24c255708.png)

There is also info pages here where we can add flatpage page
![Screenshot from 2020-07-29 14-45-49](https://user-images.githubusercontent.com/26101337/88771993-43c74600-d1aa-11ea-8702-b52f1232244e.png)
