### ISSUE TITLE
allow attendees to buy credits

### ISSUE THREAD

**Issue by gubuntu** [kartoza/prj.app#1063]
as an altenative to certifying orgs buying credits, allow attendees to purchase directly. 

1. they register
2. they buy credits
3. when they have done the course AND bought the credit, the certifying org can issue them a cert. 

Rationale: Non-EUR countries can't invoice in EUR and would lose all round on forex fees and rates. It also puts the onus and admin load on the attendee.

**Comment by ann26** [comment]
the credit system is already in place
