### ISSUE TITLE
Lesson number when using page 2

### ISSUE THREAD

**Issue by Gustry** [kartoza/prj.app#1076]
On this page, sections are from 1 to 10:
http://changelog.qgis.org/en/qgis/section/list/?page=1

If I go to page 2, I expect to start at 11, but it's starting again at 1:
http://changelog.qgis.org/en/qgis/section/list/?page=2

A minor issue ;-)

**Comment by timlinux** [comment]
Thanks @Gustry - @ann26 will you take care of this?

**Comment by ann26** [comment]
will do @timlinux
