### ISSUE TITLE
I cannot modify my company details

### ISSUE THREAD

**Issue by MyGIS** [kartoza/prj.app#1079]
Hi, I am trying to put in our company details to be approved for certification, however, I am not sure what I did wrong and it is my name that came out instead of the company name. I do not seem to find a way to make the edit. Please see attached  screenshot. 
![image](https://user-images.githubusercontent.com/5960438/69042757-c2b98b80-0a2c-11ea-993e-653f627d13f7.png)

Any idea how I could solve this? (Thanks)
Lyes

**Comment by ann26** [comment]
hi @MyGIS I have fixed the permissions and deploy this to live. Please try again and let me know if that works for you. Thank you for your patience.

**Comment by MyGIS** [comment]
Hi Anita,

 

Thanks a lot, it works! I have deleted the application under my name and left only the one with our company name. So I will just wait for the committee decision.

 

Thank you,

 

Best regards.

 

Lyes Mokraoui, 

MSBE, P.Geol., Gs.

Geospatial Consultant

GIS Innovation Sdn Bhd (557976-H)

E-6-17, Sunway Geo Avenue 2, 

Jalan Lagoon Selatan, 

Bandar Sunway, 

47500 Subang Jaya, 

Selangor Darul Ehsan, Malaysia

Tel : +603-56127025 

 <http://www.gis.com.my/> www.GIS.com.my

**Comment by linfiniti** [comment]
Thanks Lyes

@Kurt Could you take a look at Lyes’ application if it is not already on your radar?

Regards

Tim
