### ISSUE TITLE
Payment for certifying organisation credits

### ISSUE THREAD

**Issue by timlinux** [kartoza/prj.app#1090]
Currently when an org owner wants to top up their credits

![image](https://user-images.githubusercontent.com/178003/70515835-e785b800-1b2d-11ea-93b4-5d3fd01af51b.png)

they get this:

http://changelog.qgis.org/en/qgis/certifyingorganisation/qgis-kartoza-pty-ltd/top-up/

We should let the organisation managers make top ups (managers are shown here):

![image](https://user-images.githubusercontent.com/178003/70516194-814d6500-1b2e-11ea-95e6-9e4d724f78a8.png)

![image](https://user-images.githubusercontent.com/178003/70516282-a0e48d80-1b2e-11ea-9165-8c65780c0b8f.png)

So when they want to top up their credits they will click the trolly:

![image](https://user-images.githubusercontent.com/178003/70515835-e785b800-1b2d-11ea-93b4-5d3fd01af51b.png)

And then get a form where they can choose an amount of credits (let them type in a specific amount) and then do a stripe transaction where the amount paid is credit_amount_requested x credit cost (euros) which is taken from the project settings:

http://changelog.qgis.org/en/project/qgis/update/

![Screenshot 2019-12-10 at 09 25 51](https://user-images.githubusercontent.com/178003/70516599-2cf6b500-1b2f-11ea-9e53-329b8d77e2e8.png)

If you wanted to, you could make the currency used an option in the project settings too.

After payment is made, we could notify the certifcation managers (do we want this?) - or at least the treasurer unless this comes from stripe:

![image](https://user-images.githubusercontent.com/178003/70515945-156afc80-1b2e-11ea-8c27-66d60c83636a.png)

See also https://qgis.org/en/site/getinvolved/donations.html to see how donations are presented on the web site.

Also after the payment is made payee should get a confirmation (Presume stripe does this) and their credits should be updated on:

http://changelog.qgis.org/en/qgis/certifyingorganisation/qgis-kartoza-pty-ltd/

**Comment by rmarzocchi84** [comment]
Nice! We have tried it today, but IMHO there are two thing not clear: 

1) it is not clear the currency (€/$ ??)
2) 1 credit is valid for 1 attendee?

**Comment by timlinux** [comment]
@rmarzocchi84 thanks for testing!

> it is not clear the currency (€/$ ??)

It is EUR

> 1 credit is valid for 1 attendee?

Correct

@dimasciput can you please make sure these two things are clear on the purchase page?

**Comment by rmarzocchi84** [comment]
@timlinux thanks to you

![image](https://user-images.githubusercontent.com/4061154/78376593-d6762080-75ce-11ea-8882-2c7bec067b4c.png)

I think there is a problem to read the currency as you can see from the attached picture

**Comment by dimasciput** [comment]
Hi @rmarzocchi84 

It has been fixed now.

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/1979569/78416742-5050ed00-7655-11ea-99bd-0479faf76b64.png">

cc @timlinux

**Comment by timlinux** [comment]
Thanks @dimasciput !
