### ISSUE TITLE
Sustaining membership pending approval email

### ISSUE THREAD

**Issue by timlinux** [kartoza/prj.app#1101]
Thank you for your application to become a sustaining member of <org>. Your application will be reviewed by our admin team who will respond as soon as they can. If you have any queries regarding your application process please contact <sustaining membership manager>. You will receive an automated email once your application has been reviewed. If your membership is approved you can go back to the sustaining member web page to manage your subscription.

Thank you for supporting our project!

Best regards,

The <org name> team.

**Comment by dimasciput** [comment]
Updated
