### ISSUE TITLE
Unable to login 

### ISSUE THREAD

**Issue by spatialthoughts** [kartoza/prj.app#1108]
I am unable to login to projecta site for issuing certificates
https://changelog.qgis.org/en/qgis/

Alo certificate lookup by id is also failing
https://changelog.qgis.org/en/qgis/certificate/1000/

<img width="1075" alt="error" src="https://user-images.githubusercontent.com/5227506/72664648-6ec82480-3a26-11ea-9f57-77570128e47e.png">

**Comment by timlinux** [comment]
Hi Ujval

Apologies for the problem - we are busy deploying some updates (including stripe payments for certificate credits) - I am waiting for auth approval.  It should be online later. CC @dimasciput 

If it is urgent, create a non google or github based login and I will link it to your organisation.

Regards

Tim

**Comment by timlinux** [comment]
By the way, were you using Google or GitHub auth?

**Comment by spatialthoughts** [comment]
Thanks. Not super urgent, so will wait for the update to roll out.

I am using GitHub login

**Comment by timlinux** [comment]
Ok great. - we will update you here on the ticket when it is resolved.

**Comment by timlinux** [comment]
Can you try again please?

**Comment by spatialthoughts** [comment]
I am able to login now. But certificate lookup is still failing. 

I create a course and issued 7 certificates yesterday, but I don't see the course or the certificates in my organization. Attached is one of the certificates that was issued. 
[QGIS-1012.pdf](https://github.com/kartoza/prj.app/files/4080961/QGIS-1012.pdf)

**Comment by spatialthoughts** [comment]
Andreas has also issued some credits, but they seem to have disappeared as well.

**Comment by geomenke** [comment]
I was having trouble logging in via the GitHub auth today as well but this has fixed it.

**Comment by timlinux** [comment]
@geomenke note we also have Stripe payments for certificates deployed with this update

@spatialthoughts I suspect there was some lost-in-transit data as we did a backup and restore onto the new deployment. If will look on the old system for them. For your credits from Andreas - could you try out our new stripe payment system if you have not already paid @andreasneumann, otherwise I will reinstate your credits.

**Comment by dimasciput** [comment]
Hi @spatialthoughts, I have restored the certificate data, can you try again, please? Thanks.

**Comment by spatialthoughts** [comment]
Thank you @dimasciput  The restored data looks good. Closing the bug.

**Comment by spatialthoughts** [comment]
I am seeing some more issues with the system. Could be related to the migration. Have opened a new issue.
