### ISSUE TITLE
Print/Download certificate is giving 500 error

### ISSUE THREAD

**Issue by spatialthoughts** [kartoza/prj.app#1109]
Trying to print a certificate or clicking 'download all certificates issued' button gives a 500 error

Example URL: https://changelog.qgis.org/en/qgis/certifyingorganisation/spatial-thoughts/course/qgis_advanced-qgis_2020-01-18-2020-01-18/print/1161/

<img width="1104" alt="error500" src="https://user-images.githubusercontent.com/5227506/72672864-3dcc0c00-3a87-11ea-87e1-7028586c067c.png">

**Comment by dimasciput** [comment]
@spatialthoughts can you try it again please? 
cc : @timlinux

**Comment by spatialthoughts** [comment]
Print works now but download all certificates still giving 500

**Comment by timlinux** [comment]
@spatialthoughts I am going to roll back to the old server until we resolve the migration issues. Sorry for the inconvenience!
Regards

Tim

**Comment by timlinux** [comment]
@spatialthoughts ok it is reverted now - can you check if your previous entries are ok? I will assign someone to look at the 500 error tomorrow if it is also present on the old server.

**Comment by spatialthoughts** [comment]
Working fine now.

**Comment by timlinux** [comment]
Great, sorry about the hassle @spatialthoughts !
