### ISSUE TITLE
Deleting an an attendee doesn't update total count/credit

### ISSUE THREAD

**Issue by spatialthoughts** [kartoza/prj.app#1110]
I had a no-show for my course and wanted to delete the issued certificate. I was able to successfully delete the course attendee, but after deletion the credit and attendee count displayed on the organisation page remains the same. I would expect a credit to increase by 1 and attendee count decrease by 1.

https://changelog.qgis.org/en/qgis/certifyingorganisation/spatial-thoughts/

**Comment by timlinux** [comment]
In our model once a certificate is issue that transaction is completed. Normally people issue the certificate only after the course completion. Do I understand correctly that your workflow is to issue all the certificates before your course and then retract the ones that were not successful?

**Comment by spatialthoughts** [comment]
The expectation of participants (at least in India) is to get a physical certificate after completion of the course. To be able to get the printed certificates ready to be handed out at the end of the course, I issue the certificates a few days before, get them printed on a nice card stock and hand it over once the course is completed and send email with the online certificate. 

While testing the app, I saw the 'delete attendee' option and thought that button did precisely what I wanted. Delete an attendee's certificate if they didn't show up or complete the course. 

It would be good to support this workflow. I can definitely work around it by mailing the physical certificates by snail mail to those who want it.

**Comment by timlinux** [comment]
Hi

OK thanks. Maybe there should be some kind of time limit on revocation? I'm just thinking of people looking to abuse the platform somehow, though I suppose the end result would be us decertifying them if we got wind of it.

**Comment by spatialthoughts** [comment]
Thanks. Putting a time limit on revocation is a good idea.

**Comment by timlinux** [comment]
@dimasciput so you add a 'Revoke certificate' button next to each partifipant's name in the course page. When pressing that the revoke button, the organisation's credits will be incremented by one. If more than a week has elapsed since the training was completed, the revoke button should be disabled and the tooltip for it should read 'Certificate revocation with credit refund is only available for one week after the course was convened.'
