### ISSUE TITLE
Course list should use separate columns for dates

### ISSUE THREAD

**Issue by timlinux** [kartoza/prj.app#1115]
e.g. https://changelog.qgis.org/en/qgis/certifyingorganisation/lutra-consulting-ltd/

Looks ugly - can we separate the columns for dates out

![image](https://user-images.githubusercontent.com/178003/73183377-9bf59080-4112-11ea-8b37-d19a5feb1c99.png)

**Comment by dimasciput** [comment]
Fixed in https://github.com/kartoza/prj.app/pull/1118

**Comment by timlinux** [comment]
Thanks!
