### ISSUE TITLE
Course calendars should support future dates

### ISSUE THREAD

**Issue by timlinux** [kartoza/prj.app#1116]
Note picker does not let you move to future dates.

e.g. https://changelog.qgis.org/en/qgis/certifyingorganisation/lutra-consulting-ltd/create-course/

![image](https://user-images.githubusercontent.com/178003/73183821-5a191a00-4113-11ea-8e4b-1c33afba4b06.png)

**Comment by dimasciput** [comment]
Fixed in https://github.com/kartoza/prj.app/pull/1118
