### ISSUE TITLE
No Geometry Value Given

### ISSUE THREAD

**Issue by rjhale1971** [kartoza/prj.app#1119]
Maybe I'm supposed to put a lat long in the address location? I have no clue. Anyway - it won't let me move forward on this part. 

![Screenshot from 2020-01-28 10-38-43](https://user-images.githubusercontent.com/389868/73279116-9e132a00-41ba-11ea-853e-4f3056596fd7.png)

**Comment by dimasciput** [comment]
Hi @rjhale1971, thank you for the report. This issue has been fixed now, can you please try again?
