### ISSUE TITLE
Problem with some strings in certificates

### ISSUE THREAD

**Issue by saberraz** [kartoza/prj.app#1122]
I have tried to issue a certificate but it appears with the updated website, there is an issue with the strings:
![image](https://user-images.githubusercontent.com/2649047/73525076-541e8400-4406-11ea-84e7-738542b3c279.png)

**Comment by dimasciput** [comment]
Hi @saberraz , this issue has been fixed, can you please try it again? Thanks

**Comment by saberraz** [comment]
Thanks a lot for promptly fixing the issue! It works fine now.
