### ISSUE TITLE
Some letters in names appear as black boxes

### ISSUE THREAD

**Issue by saberraz** [kartoza/prj.app#1125]
see for example **ř** in here:
![image](https://user-images.githubusercontent.com/2649047/73542655-1f71f300-442d-11ea-889e-4171ec75876e.png)

**Comment by dimasciput** [comment]
Hi @saberraz , this issue should be resolved now, please try again, thanks.

**Comment by ann26** [comment]
hi @saberraz i have checked it, this problem is resolved. should you find similar problem please regenerate the certificate (next to the print button)
![Screenshot from 2020-03-04 16-44-49](https://user-images.githubusercontent.com/26101337/75866355-7fe2be80-5e37-11ea-9610-5d4bb915dc01.png)
