### ISSUE TITLE
Category names not showing when creating a changelog entry

### ISSUE THREAD

**Issue by timlinux** [kartoza/prj.app#1129]
![image](https://user-images.githubusercontent.com/178003/73742529-80a70880-4744-11ea-8d2b-5a0bcbdd3306.png)

**Comment by PeterPetrik** [comment]
+1

**Comment by peterp** [comment]
_A wild Peter appears._

**Comment by timlinux** [comment]
> A wild Peter appears.

Sorry @peterp I got overcome by name confusion there :-) Looks like another South African bumping around GitHub judging by your name :-)

**Comment by peterp** [comment]
Howzit! No problem, had a good laugh. 😂

**Comment by PeterPetrik** [comment]
well :)

**Comment by dimasciput** [comment]
Fixed and deployed : https://github.com/kartoza/prj.app/pull/1130
