### ISSUE TITLE
Uploaded gif to entry fails

### ISSUE THREAD

**Issue by timlinux** [kartoza/prj.app#1131]
https://changelog.qgis.org/en/qgis/version/3.12/#3d-mesh-layer-terrain-renderer

![mesh3d](https://user-images.githubusercontent.com/178003/73831268-f622df80-47fd-11ea-9383-6c0b44b9232b.gif)

<img width="246" alt="Screenshot 2020-02-05 at 08 44 19" src="https://user-images.githubusercontent.com/178003/73830270-4ac55b00-47fc-11ea-9706-5e097cf62331.png">

<img width="318" alt="Screenshot 2020-02-05 at 08 39 01" src="https://user-images.githubusercontent.com/178003/73830279-4dc04b80-47fc-11ea-9027-9c9521c10265.png">

**Comment by dimasciput** [comment]
@timlinux should be fixed now
