### ISSUE TITLE
PR fetcher does not get labels

### ISSUE THREAD

**Issue by timlinux** [kartoza/prj.app#1134]
<img width="634" alt="image" src="https://user-images.githubusercontent.com/178003/74485238-36dfc000-4eb2-11ea-9b16-b956ca698ebb.png">

After entering the repo url there was a brief spinner but no labels shown.

**Comment by ann26** [comment]
hi @timlinux it is because it doesn't have yet git token, you'll need git token to fetch from github api.
Could you give me the git token from kartoza account please? you can generate from this page: https://github.com/settings/tokens

**Comment by timlinux** [comment]
What permissions are needed?

![image](https://user-images.githubusercontent.com/178003/74512365-0292f080-4f00-11ea-9ceb-d22ab1e8ab17.png)


![image](https://user-images.githubusercontent.com/178003/74512384-0de61c00-4f00-11ea-892e-01afec0fb20b.png)

**Comment by ann26** [comment]
@timlinux nothing it;s fine. i've put the git token in the secret so it should be working now, please try again.
