### ISSUE TITLE
Bulk attendee upload is broken

### ISSUE THREAD

**Issue by spatialthoughts** [kartoza/prj.app#1135]
I am gettting an error uploading attendees using a CSV. I have done it successfully in the past using the same format CSV. For now, I have attended the participants manually.

Attached is my upload csv with the emails replaced with test@test.com to preserve privacy.

[attendees.txt](https://github.com/kartoza/prj.app/files/4202985/attendees.txt)

**Comment by timlinux** [comment]
@ann26 can you take a look? It is probably a side effect of our python / django update.

**Comment by timlinux** [comment]
@spatialthoughts can you try again?

**Comment by spatialthoughts** [comment]
Works now. Thanks.
