### ISSUE TITLE
Download issue certificate link is broken

### ISSUE THREAD

**Issue by spatialthoughts** [kartoza/prj.app#1138]
I get a 500 error when trying to download issued certificates from a course. Example link https://changelog.qgis.org/en/qgis/certifyingorganisation/spatial-thoughts/course/qgis_custimizing-qgis-with-python_2020-02-15-2020-02-15/download_zip/

<img width="1440" alt="download_error" src="https://user-images.githubusercontent.com/5227506/74597702-7ad8ed80-5089-11ea-9908-bb0990c7af65.png">

**Comment by ann26** [comment]
hi @spatialthoughts I fixed it, please try again.

**Comment by spatialthoughts** [comment]
Works. Thanks.
