### ISSUE TITLE
Only GH username is shown for Course Convener (not full name) so the name does not show in certificates

### ISSUE THREAD

**Issue by gioman** [kartoza/prj.app#1148]
![Screenshot_20200223_153635](https://user-images.githubusercontent.com/1951107/75114962-6cbf3a00-5652-11ea-86e1-accacbfb15e8.png)

The GH username of this person is "andremano", he has a public full name on GH, but the certificate platform does not show his full name, so when generating certificates the name does not show.

**Comment by gioman** [comment]
It seems this happens of the github user of the convener has not its first/last name filled in its github profile. Problem is that even after filling it (and logging out/in from certification platform) the full name still does not show. Not even removing/re-adding him/her as convener works as workaround.

**Comment by timlinux** [comment]
Hi

For now I fixed it manually in Admin:

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/178003/75615391-cf28a680-5b3a-11ea-9f3b-44efb707b9ce.png">


So it shows up nicely in your org:

<img width="374" alt="image" src="https://user-images.githubusercontent.com/178003/75615395-dc459580-5b3a-11ea-9269-1205d76fa9bd.png">

For a longer term fix @ann26 we need a profile page where the user can go and set their profile options like name / surname.

**Comment by gioman** [comment]
Thanks @timlinux !

**Comment by ann26** [comment]
@timlinux @gioman user profile page is added, you can edit your details there:
![Peek 2020-03-05 17-52](https://user-images.githubusercontent.com/26101337/75981043-3ddc7a00-5f16-11ea-9b75-17b8459b9203.gif)

**Comment by timlinux** [comment]
Awesome, thanks @ann26

**Comment by gioman** [comment]
@timlinux @ann26 thanks!
