### ISSUE TITLE
Cannot upload a CSV with attendees list

### ISSUE THREAD

**Issue by gioman** [kartoza/prj.app#1149]
The CSV is formatted as requested:

![Screenshot_20200229_092926](https://user-images.githubusercontent.com/1951107/75604993-57289500-5ad6-11ea-925b-f17cd3479369.png)

**Comment by gioman** [comment]
Header row had blank spaces, after removing them upload went ok.

**Comment by timlinux** [comment]
Can you attach the broken one here please that we can trap for these kind of errors.Thanks!

**Comment by gioman** [comment]
@timlinux 

the wrong CSV was like:

name ,lastname ,email 
john,doe,jhondoe@domain.org
jane,doe,janedoe@domain.org

the accepted one:

name,lastname,email
john,doe,jhondoe@domain.org
jane,doe,janedoe@domain.org

**Comment by ann26** [comment]
should be working now even using the wrong csv, please try again.
