### ISSUE TITLE
Template image does not stick

### ISSUE THREAD

**Issue by gioman** [kartoza/prj.app#1150]
After uploading a template image and clikcing "preview" the certificate preview is ok

![Screenshot_20200229_095710](https://user-images.githubusercontent.com/1951107/75605357-01ee8280-5ada-11ea-9183-024a766543f2.png)

but after saving with "submit" and then editing the training the template image is gone

![Screenshot_20200229_095842](https://user-images.githubusercontent.com/1951107/75605369-1894d980-5ada-11ea-9104-ee0afa74c011.png)

and the preview does not contains the template image (no logos on the right)

![Screenshot_20200229_100016](https://user-images.githubusercontent.com/1951107/75605385-572a9400-5ada-11ea-9756-0ade1372c006.png)

Not sure if this affects also the real creation/issuing of certificates.

**Comment by timlinux** [comment]
Maybe a full disk @ann26 ?

**Comment by timlinux** [comment]
No not full, I checked. @gioman can you share the template you were trying to upload please?

Thanks

**Comment by gioman** [comment]
@timlinux attached

![template](https://user-images.githubusercontent.com/1951107/75623171-74756600-5b9f-11ea-8414-19e2fea2b955.png)

**Comment by ann26** [comment]
should be working now @gioman

**Comment by gioman** [comment]
@ann26 thanks!
