### ISSUE TITLE
Error (500) opening/editing training center

### ISSUE THREAD

**Issue by gioman** [kartoza/prj.app#1151]
We have a couple of different  training centers with a similar name:

![Screenshot_20200229_130302](https://user-images.githubusercontent.com/1951107/75608261-df6a6280-5af5-11ea-8ee1-1714af4c1328.png)

but the link to them is identical, clicking it or pressing edit button (link also identical) causes error 500.

**Comment by timlinux** [comment]
Can you take a look please @ann26 

@gioman can you share the specific link that took you to a 500 error please?

Thanks

**Comment by timlinux** [comment]
For short term fix, I changed the slug for porto1

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/178003/75615586-81616d80-5b3d-11ea-8065-3a1c6577e303.png">


The tooltip shows it leads to a valid link now:

<img width="664" alt="image" src="https://user-images.githubusercontent.com/178003/75615596-aa81fe00-5b3d-11ea-9591-5ed5360088f0.png">

The link to the center now works:

https://changelog.qgis.org/en/qgis/certifyingorganisation/natural-gis-lda/trainingcenter/porto1/

**Comment by gioman** [comment]
Thanks!

**Comment by ann26** [comment]
I tried to recreate the problem to no avail, usually when you created a training center it will prevent you to have the same name to prevent the same slug. So I don't know how the problem raises in the first place. I will close this issue for now.
