### ISSUE TITLE
Sign up link for certification is broken when not logged in

### ISSUE THREAD

**Issue by timlinux** [kartoza/prj.app#1152]
IF a user visits https://changelog.qgis.org/en/qgis/create-certifyingorganisation/ and they are not logged in, they get redirected to the front page. They should instead get shown a page asking them to log / create an account first and then get redirected back to the create page. They should also be shown the help link so they can find out how the certification system works.

**Comment by timlinux** [comment]
cc @andreasneumann @geomenke

**Comment by andreasneumann** [comment]
Yes, happens to me as well if I sign out and pretend to be a new user who knows nothing about the system. Quite confusing. Thanks for improving this!

**Comment by timlinux** [comment]
Same issue with sustating member sign up

**Comment by ann26** [comment]
@timlinux @andreasneumann should be working now
