### ISSUE TITLE
Info page workflow

### ISSUE THREAD

**Issue by timlinux** [kartoza/prj.app#1157]
For certification:

![image](https://user-images.githubusercontent.com/178003/75864719-5b1c2600-5dfa-11ea-9008-bd643be06711.png)

Add a menu item above others called 'Learn about certification'

That takes us to a flat page. On the flat page I will edit some general information about the certification system - I will include a link to https://changelog.qgis.org/en/qgis/about/ on that page.

For Sustaining members:

![image](https://user-images.githubusercontent.com/178003/75864899-9dddfe00-5dfa-11ea-9653-d669076fa7aa.png)

 'Learn about sustaining membership programme'

Takes us to a flatpage where we can manage the content

**Comment by anitanh** [comment]
this is already done
![Screenshot from 2020-07-29 14-43-13](https://user-images.githubusercontent.com/26101337/88771740-e16e4580-d1a9-11ea-9dec-9f3a99488a45.png)
![Screenshot from 2020-07-29 14-43-19](https://user-images.githubusercontent.com/26101337/88771743-e206dc00-d1a9-11ea-9159-ab963ae84cba.png)
