### ISSUE TITLE
Validation incorrect on version admin form for slug

### ISSUE THREAD

**Issue by timlinux** [kartoza/prj.app#1163]
A slug that is accepted in the frontend is refused in the backend. This means you cannot edit existing Versions in admin

<img width="994" alt="image" src="https://user-images.githubusercontent.com/178003/76130875-3bf0e480-6004-11ea-8348-e4dd4eebb5a4.png">

**Comment by ann26** [comment]
hi @timlinux I've fixed it, please try again
