### ISSUE TITLE
rst export currently broken for QGIS 3.12

### ISSUE THREAD

**Issue by rduivenvoorde** [kartoza/prj.app#1164]
Somebody with the right permissions should be able to download the rst+images in a zip:

https://changelog.qgis.org/en/qgis/version/3.12/download/

This morning it throws a 500 error.

**Comment by ann26** [comment]
hi @rduivenvoorde it's fixed now, please try again

**Comment by rduivenvoorde** [comment]
@ann26 Cool Thanks!
Just tested, but somethings changed in the rest...

`index.rst:1552:Duplicate substitution definition name: "image".`

If you look into the rst you see a lot of the image names (in the substitutions at the bottom) are named 'image' I think in earlier versions they had a number image1, image2 etc.. like most of the other images.

Is this easy to fix?
Else I have to change them all by hand :-(
But if this is a problem I will...

**Comment by ann26** [comment]
hi @rduivenvoorde I will have a look

**Comment by ann26** [comment]
hi @rduivenvoorde I see in the rst that the images have numbers on them...

**Comment by rduivenvoorde** [comment]
Hi @ann26 

In index.rst I have for example:

```
A new menu entry (Actions on selection) is added to the layer tree context menu. It is shown only when required (layer has selection and actions can be run on the given layer).

|image|
```

and on the bottom of the index.rst you see there are several images with name `|image|`. I'm not sure if the `|Peek 2019-12-08 09-18|` names will work, but will try later.

```
.. |image0| image:: images/projects/4ba1280c5037bc85ccedcbd39dab18eb725729c5.png
.. |image1| image:: images/projects/dbf38cfe3b603e7e0b840336d39b399a1a46e52d.png
   :class: img-responsive img-rounded center-block
.. |image| image:: https://user-images.githubusercontent.com/127259/74035907-7f334580-49bb-11ea-8d2d-b99eaa10aa89.png
.. |Peek 2020-01-14 16-06| image:: https://user-images.githubusercontent.com/1829991/72318360-cd6c6600-36e7-11ea-9f2d-9a47d8772623.gif
.. |Peek 2020-01-09 11-08| image:: https://user-images.githubusercontent.com/1829991/72029046-5fcbce80-32d0-11ea-8571-0ae8fa8e3bb0.gif
.. |image5| image:: images/entries/48c75d20d3805af3dad8c7faae3c3786a8f6fed0.gif
   :class: img-responsive img-rounded
.. |image| image:: https://user-images.githubusercontent.com/127259/72597971-2bc75d80-390f-11ea-84af-7f2c25d5568a.png
.. |copy-dialog\_2| image:: https://user-images.githubusercontent.com/28384354/72243171-7e410b00-35eb-11ea-8903-11bd56cd9da6.gif
.. |copy\_paste\_single| image:: https://user-images.githubusercontent.com/28384354/72243125-5ce01f00-35eb-11ea-897e-0bccdcf083d7.png
.. |Peek 2019-12-20 11-27| image:: https://user-images.githubusercontent.com/1829991/71222288-b7070080-231b-11ea-89f4-af856dece4c3.gif
.. |image10| image:: https://user-images.githubusercontent.com/142164/68952420-1bd0b780-07c0-11ea-88d1-2ad0a8b5591e.gif
.. |image11| image:: images/entries/5b772e74d433e766b50023cd107aad9cb1d68de6.png
   :class: img-responsive img-rounded
.. |image12| image:: https://user-images.githubusercontent.com/1618556/62111873-d68c8680-b2b1-11e9-8cd4-19077f99a8ff.gif
.. |Peek 2019-12-08 09-18| image:: https://user-images.githubusercontent.com/588407/70386652-acec1600-199b-11ea-8457-f9dd54c84272.gif
.. |Peek 2019-12-08 09-16| image:: https://user-images.githubusercontent.com/588407/70386651-acec1600-199b-11ea-8ce2-27798aec38a7.gif
```
I now see there are just 4 'image' names doublures, I can rename by hand, but it's strange these do not get a number...

**Comment by ann26** [comment]
hi @rduivenvoorde I think the duplicate 'image' names are because the image is hosted from another server (github), Although I still don't understand why some of them have numbers and some don't. Also some images names retain their original names. I will continue investigate and keep you posted.

**Comment by timlinux** [comment]
@rduivenvoorde ouch if those are an issue I guess I will download them and insert them into the entries manually or something
