### ISSUE TITLE
[feature request] allow fixing typos in attendees names

### ISSUE THREAD

**Issue by gioman** [kartoza/prj.app#1169]
Not sure if I'm missing something obvious:

1) I add an attendee 

2) I emit the certificate, credits goes down by 1

3) opsss, then name has a typo

4) I can't edit his name and re-issue the same certificate with the correct name and without using another credit

5) I re-add the attendee with the correct name, re-issue a new certificate and spend another credit in the process

cheers!

**Comment by timlinux** [comment]
Ouch. In the mean time I can refund your credit and / or fix the name. I think your request will be resolved when we implement #1110 

Regards

Tim

**Comment by gioman** [comment]
>  In the mean time I can refund your credit

@timlinux no need Tim! I'm happy giving the extra 20€ to QGIS!

**Comment by gioman** [comment]
> resolved when we implement #1110

yeah, now I think that this is actually a duplicate of it, feel free to close.
