### ISSUE TITLE
Change users name after issuing certificate

### ISSUE THREAD

**Issue by nickbearman** [kartoza/prj.app#1172]
Hi,

I've issued some certificates but now one of the participants wants a different name on their certificate. I've removed them from the course, but how do I change their name? If I add a new person I end up using another credit!

Thanks.

**Comment by timlinux** [comment]
@nickbearman I will refund your credit. We have a ticket to support what you want to do (see #1110)

**Comment by timlinux** [comment]
@nickbearman oh what organisation is it that you need the credit returned for?

**Comment by nickbearman** [comment]
Thanks @timlinux 
Please refund 1 credit to Geospatial Training Solutions. 
Thanks for the link to the other issue - I must have missed it!

**Comment by timlinux** [comment]
@nickbearman ok done - I am going to close this in favour of #1110

**Comment by nickbearman** [comment]
Thanks, makes sense, fine with me. N.

**Comment by nickbearman** [comment]
Just checked my balance, and it is 8 credits, whereas it was 9 previously (and should be 10 with the change). @timlinux did you add the credit ok? 
(I am going to issue a certificate now, so it will go down one.)
Thanks.

**Comment by timlinux** [comment]
@nickbearman it was at 7 and I set it to 8.  I've updated it to 10 now.

**Comment by nickbearman** [comment]
Thanks, much appreciated. Sorry if I got it wrong.
