### ISSUE TITLE
Allow online training center

### ISSUE THREAD

**Issue by spatialthoughts** [kartoza/prj.app#1173]
I am planning to offer my certification courses as a live online class. It isn't clear how to set it up as a new training center. Would be good to have an option of an 'online' training center than one associated with a physical address.

**Comment by timlinux** [comment]
Thanks for the suggestion, I will add it to the TODO list - in the mean time I suggest to create a center called 'online' with generic info / misuse the address to indicate that it can be attended from anywhere.
