### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by cchristelis** [kartoza/prj.app#349]
# Problem

Currently staff users need to approve projects etc. This will no scale well.
# Proposed solution

The first person to claim a project (validate this through github) becomes the `Project Owner`. The `Project Owner` can assign `Project Administrator` and `Project Collaborators`.

**Comment by meomancer** [comment]
- [ ] automatically assign project owner based on github project when approve the project
- [ ] create relationship for administrator and collaborator
- [ ] create page for assigning administrator and collaborator

**Comment by meomancer** [comment]
@cchristelis @timlinux 
i face blocker for this issue,
i made Project Administrator model that link user and project 

i dbrestore from dmp from kartoza5
but when i migrate, it said:
`django.db.utils.ProgrammingError: there is no unique constraint matching given keys for referenced table "base_project"`
i check database and it seems that no constraint on the table

and when i drop/create gis and migrate without dbrestore, it is working fine

I am not sure how to do to fix it

**Comment by cchristelis** [comment]
@meomancer, the migrations are broken. I had to fake my way around the migrations to get this to work on my machine.

**Comment by timlinux** [comment]
@meomancer you should work from a dump from inasafe-docker server. You can get one using ``make dbsync; make mediasync`` inside the deployment folder but I think you don't have login rights to that machine. I will make a btsync to share these to you.

**Comment by timlinux** [comment]
Ok I sent you details on how to collect the media and db data via btsync containers.

**Comment by meomancer** [comment]
@cchristelis yes, i don't know how to fix it
i just uses base.project as foreign key, and it cannot be migrated with dumped data
`django.db.utils.ProgrammingError: there is no unique constraint matching given keys for referenced table "base_project"`
i saw on postgree that base.project doesn't has unique contraint in it.
