### ISSUE TITLE
Integrate payment platform

### ISSUE THREAD

**Issue by cchristelis** [kartoza/prj.app#399]
# Problem

Users need to pay for the certificate.

# Proposed solution

Integrate payment platform and get user payment.

**Comment by cchristelis** [comment]
# Also see
- https://micropyramid.com/blog/django-payu-payment-gateway-integration/
- https://djangopackages.org/grids/g/payment-processing/

**Comment by cchristelis** [comment]
Please investigate to the point where you can make a recommendation.

**Comment by jeanabdesmidt** [comment]
Payment gateway systems supported in South Africa that integrate easily with Django Apps: include
Paygate
PayU
Payfast
Mygate

From the list above only PayU seems to support International payments - still need to verify and contact for payment structures.
Paygate offers 4 payment options depending on the business scale ranging from a R0 monthly fee with high 3.9% per transaction to R500 monthly 0.25% transaction.
Payfast is mostly a flexible service that has no maintenance/monthly fees and you only pay per transaction. Not recommended if the amount of sales can justify a subscription based service.
Mygate offers 4 payment options all of which include a setup and monthly costs, but limited free transactions. Pay per transaction only kicks in after free transactions are used.

https://www.payu.co.za/
https://www.paygate.co.za/
https://mygate.co.za/payment-solutions/payment-gateway/pricing/
https://www.payfast.co.za

Conclusively
Estimated sales for certificates should be taken in account when choosing a payment gateway
PayU South African pricing must still be verified
International support must be verified
Most subscriptions are credit card transactions
Should we also support cryptocurrencies?

**Comment by jeanabdesmidt** [comment]
@cchistelis see above

**Comment by jeanabdesmidt** [comment]
Also see Braintree and Stripe. Pay as you go option for 2.9% and .30$.

**Comment by gubuntu** [comment]
Why not Paypal too? One can do Paypal account and credit card transactions through PayPal and it will suit the international market nicely.

**Comment by cchristelis** [comment]
https://django-stripe-payments.readthedocs.io/en/latest/
