### ISSUE TITLE
500 Error when deleting an organization in the moderation queue

### ISSUE THREAD

**Issue by timlinux** [kartoza/prj.app#490]
On 1.6.2 deleting an organization in the moderation queue gives a 500 error.

I also get a similar error when trying to approve a certifying organization.

**Comment by ann26** [comment]
Hi @timlinux , are you still experiencing this error?
I only got the error once, and that was when the migrations in production in my local was not updated, so when I `make reload` I didn't get the error again. But I'll continue to investigate this error.

**Comment by ann26** [comment]
Hi @timlinux , I haven't been able to reproduce the error again. I tried in the production in my local and in live site but everything seems to be working.. I am not sure why this error happens. 
Please let me know if you still get this error.
