### ISSUE TITLE
[feature] Allow to generate all certificates for one course in one click

### ISSUE THREAD

**Issue by mbernasocchi** [kartoza/prj.app#757]
in courses with many participants can be tedious to generate the certificates one at a time.

**Comment by sonlinux** [comment]
Hi @timlinux 
Am trying to understand what the ticket is refering to this case as for regeneration of all certificates in one click is implemented already as shown below.

![generate_certificate](https://user-images.githubusercontent.com/10270148/36885811-d7d7c0be-1df1-11e8-85e8-397fe33381f9.png)

Am I missing something?
Thanks

**Comment by cchristelis** [comment]
Is this requesting an "issue all" directive @mbernasocchi?

**Comment by mbernasocchi** [comment]
hi @cchristelis yes

**Comment by sonlinux** [comment]
Hi @mbernasocchi 
Ill get to work on it.
Thanks.

**Comment by anitanh** [comment]
hi @mbernasocchi sorry for the very long wait! I finally made it happen here: https://github.com/kartoza/prj.app/pull/1214
