### ISSUE TITLE
Remove Pending State for Version, Category, and Entry

### ISSUE THREAD

**Issue by ismailsunni** [kartoza/prj.app#806]
It turns out the approach to have pending state doesn't work properly. After discussion, @timlinux suggests removing the pending state for:
- [x] Version
- [x] Category
- [x] Entry

It will have these consequents:
- [x]  All normal user can not edit or add anything
- [x] Edit will happen directly after click save (no more pending state)
- [x] Only staff, superuser, project owner and version manager can make edits

**Comment by timlinux** [comment]
Can you make this happen this week @ismailsunni ?
