### ISSUE TITLE
Fix query in atom fee

### ISSUE THREAD

**Issue by rduivenvoorde** [kartoza/prj.app#903]
If I'm right, the current sponsors atom/rss feed returns records of both current sponsor 'contracts' and earlier ones. 
As an example: in the feed:
http://changelog.qgis.org/en/qgis/sponsors/rss/
you'll see the Swiss gold sponsor twice (but I think that is for all returning sponsors)

We should filter out 'old' contracts which are not valid anymore.

Note that in practice I use atom at this moment

@ann26 
@andreasneumann 
feel free to contact me if not clear

**Comment by rduivenvoorde** [comment]
For the 'Past Sponsors' I created a PR: https://github.com/kartoza/prj.app/pull/931

About the double entries: I found out that that you see some sponsors twice appears to be a data problem. If you go to:

http://changelog.qgis.org/en/site-admin/changes/sponsorshipperiod/

in the 'table' Sponsorship periods you can see 2 records for the below
mentioned. 

Can I just remove them via that admin interface?
Or should I do that via
http://changelog.qgis.org/en/qgis/sponsorshipperiod/list/

OSGeo:UK 	2500.00 EUR 	March 16, 2018 - March 16, 2019 	
OSGeo:UK 	2500.00 EUR 	March 16, 2018 - March 1, 2019

Gaia3D, Inc. 	500.00 EUR 	May 1, 2018 - May 1, 2019 	
Gaia3D, Inc. 	500.00 EUR 	May 1, 2018 - May 1, 2019

Royal Borough of Windsor and Maidenhead 	500.00 EUR 	April 1, 2018 -
April 1, 2019 	
Royal Borough of Windsor and Maidenhead 	500.00 EUR 	April 1, 2018 -
April 1, 2019

**Comment by ann26** [comment]
Hi @rduivenvoorde ,
You can do that via http://changelog.qgis.org/en/qgis/sponsorshipperiod/list/, click on the `eye` button and you'll see the details page of it where you can edit or remove that.

**Comment by rduivenvoorde** [comment]
Thanks @ann26 , I will close this issue then. I think @andreasneumann should do this then as he knows the finesses of QGIS finances.
