### ISSUE TITLE
Download as rst broken/raises 500 error

### ISSUE THREAD

**Issue by rduivenvoorde** [kartoza/prj.app#910]
Hi, Trying to download the visual changelog 3.0  as rst to incorporate it in the website, I get a 500 error, telling me:
If you need assistance, you may reference this error as bfa67a6ae7fe4d728f541e92fd134089.
![selection_442](https://user-images.githubusercontent.com/731673/39743606-b4e79e50-52a1-11e8-9ea4-60a95b8944c5.png)
![selection_443](https://user-images.githubusercontent.com/731673/39743616-b8df4e18-52a1-11e8-9b54-e908b210a259.png)

**Comment by ann26** [comment]
hi @timlinux I think the culprit are these images from the page:
![screenshot from 2018-05-08 16-21-47](https://user-images.githubusercontent.com/26101337/39749202-43613904-52dc-11e8-8fe6-401207ee10c0.png)

they are in the descriptions and are url to images in github.
```
![as323](https://user-images.githubusercontent.com/9266424/29836108-180924ee-8cec-11e7-8845-91436b9477cd.png)
```
and
```
![as00](https://user-images.githubusercontent.com/9266424/29835982-9d85468a-8ceb-11e7-90cc-2bd28f441c9a.png)
```

therefore when the system tried to download it from the server, it couldn't found it.

**Comment by rduivenvoorde** [comment]
Can we download those images and just upload them? Instead of pointing to the github versions?

**Comment by rduivenvoorde** [comment]
FYI I want to move on, so I removed this two images. And added the largest one as normal image to the item.
Now it downloads fine.
Ok for now for me

**Comment by rduivenvoorde** [comment]
Mmm, but now the download is no 'plain' rst anymore.

It is now a mostly consisting of ` .. raw:: html ` parts...

Is this fixable?

**Comment by rduivenvoorde** [comment]
Trying to look a little into this myself. If I am correct:
- I think here:
https://github.com/kartoza/projecta/blob/develop/django_project/changes/views/version.py#L682-L692
The list of items is converted/rendered to html first. This html seems highly customized to be viewed in some responsive way ..
- Then pandoc is asked to convert this (complex) html to rst, and is actually failing. Still valid rst, but with A LOT of `.. raw:: html` parts, actually making it useless for Sphinx.
Earlier versions (after some cleanup) looked like this:
https://raw.githubusercontent.com/qgis/QGIS-Website/master/source/site/forusers/visualchangelog260/index.rst

I'm wondering if it is maybe possible to leave out the pandoc conversion, but just render a simple rst-template?
OR create a very simple html template so we can get normal rst back?

OR is this part actually also used for other uses?? Like downloading rst for for example sponsorlists or so???

@timlinux @ann26 what do you think?
