### ISSUE TITLE
duplicate certificates

### ISSUE THREAD

**Issue by timlinux** [kartoza/prj.app#916]
We have 4 certs that are duplicates:

```
gis=# select "certificateID", count("certificateID") as count from certification_certificate group by "certificateID" order by count desc;
 certificateID | count 
---------------+-------
 QGIS-135      |     2
 QGIS-136      |     2
```

which gives an error fetching the certs:

```
        if queryset is None:
            queryset = self.get_queryset()
            certificateID = self.kwargs.get('id', None)
            if certificateID:
                try:
                    obj = queryset.get(certificateID=certificateID)
                    return obj
                except Certificate.DoesNotExist:
                    return None
            else:
                raise Http404('Sorry! Certificate by this ID is not exist.')
```

See http://sentry.kartoza.com/sentry/projecta/issues/147/

**Comment by ann26** [comment]
Hi @timlinux , sorry for this inconvenience. I fixed the other duplicates just now (there were two QGIS-139) so I changed one of it to be QGIS-141 then I regenerated the certificate so the verification link is updated. I also have written to them. 

Sorry again!

**Comment by timlinux** [comment]
Thanks @ann26 - so the fix is permanent now? Please re-open if not....

**Comment by ann26** [comment]
I believe so @timlinux
