### ISSUE TITLE
Downloading Tiles results in a 404 error

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/prj.app#918]
# Problem
When in data download section choosing tiles results in the following error message.
![downl-admin](https://user-images.githubusercontent.com/2510900/40232110-cbb24172-5a9d-11e8-8d1b-e31055a5983d.png)

# solution
Make it happy and try not to open the XYZ tiles in a browser but rather a popup message with the URL would suffice and an option to copy the url

**Comment by timlinux** [comment]
Wrong repo @NyakudyaA ?

**Comment by NyakudyaA** [comment]
Ohh did not see that. Will migrate it now to Geosafe

**Comment by NyakudyaA** [comment]
This issue was moved to kartoza/geonode#430
