### ISSUE TITLE
Download QGIS 3.2.0 as rst broken/raises 500 error

### ISSUE THREAD

**Issue by rduivenvoorde** [kartoza/prj.app#932]
If you download rst for QGIS 3.2.0 you get a 500.

If I do the same in my dev env, I see:

```
MultipleObjectsReturned at /en/qgis/version/3.2.0/download/
get() returned more than one Version -- it returned 2!
```
And furter in the debug info:

![selection_476](https://user-images.githubusercontent.com/731673/40545312-abdac098-602b-11e8-838c-f14aebd72b98.png)

which to me looks like there is not enough info to select ONLY QGIS (as InaSAFE 3.2.0 is also coming though)?

Any pointers to fix this are appreciated

**Comment by timlinux** [comment]
See also http://sentry.kartoza.com/sentry/projecta/issues/236/
