### ISSUE TITLE
We need tweaks for past sponsors

### ISSUE THREAD

**Issue by timlinux** [kartoza/prj.app#936]
See #931

Can you add the past sponsors button and also a test so that our coverage is not reduced? Please make it a meaningful test that inserts some current and expired sponsors and tests we get back the correct set from each feed. Than merge.

Also please make a view like the current sponsors view which shows all the historidcal sponsors for a project,

**Comment by ann26** [comment]
Hi @timlinux I added the button for past sponsor rss and the tests too in #940 

for this one:
```
Also please make a view like the current sponsors view which 
shows all the historical sponsors for a project,
```
The current sponsors view has past sponsor list at the bottom part. Do you want it to be combined together as one list in historical order?
