### ISSUE TITLE
MemoryError When Creating Certificates

### ISSUE THREAD

**Issue by ismailsunni** [kartoza/prj.app#943]
See the sentry entries: http://sentry.kartoza.com/sentry/projecta/?query=is%3Aunresolved+memoryerror

As far as I remember there are at least 3 occasion this memory error occurs:
1. Preview certificate for a course
2. Bulk download certificate for a course as zip file
3. Create certificate / Regenerate certificate for an attende

Projecta will give you 504, but no other information.

The first time I got this error, the docker seems hanging. I need to restart the docker service.

**Comment by timlinux** [comment]
Maybe the template is too big? Can you reduce the size of it? If needed we will have to increase the size of the cloud server.
