### ISSUE TITLE
Logic Error in CSV Attendee Uploader

### ISSUE THREAD

**Issue by ismailsunni** [kartoza/prj.app#944]
It works for the first time, but if you have the same attendee for the same organization, it will not work and fail to upload all of the attendees in the CSV.

I tried to fix it, but I didn't consider the atomic transaction decorator.

**Comment by haubourg** [comment]
Confirmed, If an attendee is already registered, it is not added to the course by the bulk CSV update.

**Comment by timlinux** [comment]
Thanks @haubourg . @ann26 can you add this to your todo list please?

**Comment by ann26** [comment]
fixed here: https://github.com/kartoza/prj.app/pull/1154

**Comment by haubourg** [comment]
Thanks @ann26 !
