### ISSUE TITLE
Certificate - i18n problem with Training Center name

### ISSUE THREAD

**Issue by Cracert** [kartoza/prj.app#955]
Funny polish S in center name

![tcenter-ok](https://user-images.githubusercontent.com/630667/41259734-f9450efe-6dd4-11e8-9ef6-a5d1d82e5c19.png)

becomes black square in preview

![tcenter-cert](https://user-images.githubusercontent.com/630667/41259742-feb53ed6-6dd4-11e8-8505-95f7410bcf9e.png)

**Comment by Cracert** [comment]
The same issue when rendering final certificate.

**Comment by anitanh** [comment]
It's fixed now
