### ISSUE TITLE
Certificate - two similar courses raise 500 error

### ISSUE THREAD

**Issue by Cracert** [kartoza/prj.app#956]
We have two similar courses - the same name, period, center. But two different conveners. I defined without a problem second course. Entry 2 and 3 on [our courses page](http://changelog.kartoza.com/en/qgis/certifyingorganisation/qgis-cracow-university-of-technology/).

But those two almost identical entries are impossible to edit/view/delete. 

Reference errors raised by Django are `7d50c658e4a644d9a4ac580f97f70ea0` and `a8c4d3d667cc424f905b73cc31376cfa`.

For testing purposes I have created one more course (4 entry), but changed period. This course is editable and works fine.

**Comment by timlinux** [comment]
Full traceback for these errors is here:

For viewing:

http://sentry.kartoza.com/sentry/projecta/issues/290/

**Comment by timlinux** [comment]
updating:


http://sentry.kartoza.com/sentry/projecta/issues/36/

deleting:
http://sentry.kartoza.com/sentry/projecta/issues/291/

@Cracert we will try to fix ASAP
