### ISSUE TITLE
Fields in the lesson app have a character limit

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/prj.app#958]
# Problem
I am busy editing content in the [qgis-lesson1](http://changelog.qgis.org/en/qgis/section/introduction-qgis-1/print/73/) on the summary leader section.
![screen shot 2018-06-12 at 15 39 06](https://user-images.githubusercontent.com/2510900/41293904-e34b1760-6e56-11e8-8ad5-c941959dc8a9.png)

The text is cut off and different from the original pdf in the Training manual.
# solution
Fix and increase the character limit

**Comment by timlinux** [comment]
@NyakudyaA the summary leader should be a short sentence only. Rather move the extended content into the summary text.
