### ISSUE TITLE
We should not show 'future' sponsors

### ISSUE THREAD

**Issue by rduivenvoorde** [kartoza/prj.app#972]
See https://github.com/qgis/QGIS-Website/issues/550#issuecomment-405466754

Sometimes there are sponsor records in future, we should create a  query to NOT have those in results

**Comment by timlinux** [comment]
I guess this is just for the feed right?

**Comment by rduivenvoorde** [comment]
@andreasneumann @timlinux  if I understand Andrea's comment on  qgis/QGIS-Website#550 right, it should just not show up in generated html lists too?

But this kind of list, well, depending on the function of it:
http://changelog.qgis.org/en/qgis/sponsors/list/
should show it (if it is used by Andreas to edit items), or NOT show it if it is to be viewed by 'normal' users.

But to fix THIS issue now, I would only do it for the feed for now (Andreas?).
