### ISSUE TITLE
[certification] certification preview doesn't show "trained competence"

### ISSUE THREAD

**Issue by yjacolin** [kartoza/prj.app#984]
Here a screenshot:
![spectacle b25744](https://user-images.githubusercontent.com/660191/46737648-581c1500-cc9c-11e8-9185-cabb20d144d0.png)

"trained competence" field is empty!

**Comment by gioman** [comment]
Confirmed also here.

**Comment by anitanh** [comment]
Already fixed
![Screenshot from 2020-07-30 14-23-30](https://user-images.githubusercontent.com/26101337/88893248-455b4180-d270-11ea-9c06-dafed286a742.png)
