### ISSUE TITLE
[certification] Credits update after deleting certificate

### ISSUE THREAD

**Issue by Cracert** [kartoza/prj.app#999]
During initial phase of certification I have created wrong certificate (164), and then the good one (167). Today I deleted first version, but credits didn't change.

Both certificates are still visible in changelog, but not in my certification panel.
Should certificates be deleted this way if something goes wrong? What policy do we have for such cases?

**Comment by anitanh** [comment]
we have the revoke certificate system now (https://github.com/kartoza/prj.app/pull/1209), you can revoke the certificate and you'll get a refund for that certificate to your credits
